version: "3"

services:

  https-nginx:
    env_file:
      - domain.env
    build: https-nginx
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /var/www/html/:/var/www/html/:ro
      - /var/log/nginx/:/var/log/nginx/
    command: nginx
    links:
      - influx-db

  certbot:
    stdin_open: true
    tty: true
    build: certbot
    ports:
      - 0.0.0.0:443:443
      - 0.0.0.0:80:80
    volumes:
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
