version: "3"

services:

  https-nginx:
    env_file:
      - domain.env
    build: https-nginx
    ports:
      - "443:443"
    volumes:
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /var/www/html/:/var/www/html/:ro
      - /var/log/nginx/:/var/log/nginx/
    command: nginx

  influx-db:
    build: influx-db
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /var/lib/influx-db:/var/lib/influx-db/
      - /var/log/influxdb/:/var/log/influxdb/

  certbot:
    stdin_open: true
    tty: true
    build: certbot
    ports:
      - 0.0.0.0:443:443
      - 0.0.0.0:80:80
    volumes:
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
