version: "3"

services:

  nginx:
    build: docker-nginx
    ports:
      - 0.0.0.0:443:443
    volumes:
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /var/www/html/:/var/www/html/:ro
      - /var/log/nginx/:/var/log/nginx/

  certbot:
    stdin_open: true
    tty: true
    build: docker-certbot
    ports:
      - 0.0.0.0:443:443
    volumes:
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
